project1/urls.py
from django.contrib import admin
from django.urls import path,include

#lali's code
from django.conf.urls import url
from boards import views
from accounts import views as accounts_views
from django.contrib.auth import views as auth_views

#end of lali code

urlpatterns = [

    url(r'^admin/',admin.site.urls),
    url(r'^$', views.BoardListView.as_view() ,name='home'),
    url(r'^signup/$', accounts_views.signup , name = 'signup'),
    url(r'^login/$',auth_views.LoginView.as_view(template_name = 'login.html'),name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(),name='logout'),
    url(r'^boards/(?P<pk>\d+)/$', views.TopicListView.as_view(), name='board_topics'),
    url(r'^boards/(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    url(r'^reset/$',auth_views.PasswordResetView.as_view(
        template_name = 'password_reset.html',
        email_template_name = 'password_reset_email.html',
        subject_template_name = 'password_reset_subject.txt'
    ),name='password_reset'),

    url(r'^reset/done/$',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),

    url(r'^reset/complete/$',auth_views.PasswordResetCompleteView.as_view(
        template_name = 'password_reset_complete.html'
    ),name='password_reset_complete'),

    url(r'^settings/password/$',auth_views.PasswordChangeView.as_view(
        template_name='password_change.html'
    ),name='password_change'),

    url(r'^settings/password/done/$',auth_views.PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'
    ), name='password_change_done'),

    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.PostListView.as_view(),name='topic_posts'),

    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', views.reply_topic,
        name = 'reply_topic'),

    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',
        views.PostUpdateView.as_view(),name='edit_post'),

    url(r'^settings/account/$', views.UserUpdateView.as_view(),name='my_account'),

]

boards/models.py
from django.db import models
from django.utils.text import Truncator
# Create your models here.
#start of l code
from django.contrib.auth.models import User
from django.utils.html import mark_safe
from markdown import markdown
import math

class Board(models.Model):
    name = models.CharField(max_length=30,unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_posts_count(self):
        return Post.objects.filter(topic__board=self).count()

    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name='topics',on_delete=models.DO_NOTHING)
    starter = models.ForeignKey(User, related_name='topics',on_delete=models.DO_NOTHING)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.subject

    def get_page_count(self):
        count = self.posts.count()
        pages = count / 4
        return math.ceil(pages)

    def has_many_pages(self,count = None):
        if count is None:
            count = self.get_page_count()
        return count > 6

    def get_page_range(self):
        count = self.get_page_count()
        if self.has_many_pages(count):
            return range(1,5)
        return range(1,count + 1)

    def get_last_ten_posts(self):
        return self.posts.order_by('-created_at')[:10]

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts',on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name='posts',on_delete=models.DO_NOTHING)
    updated_by = models.ForeignKey(User, null=True, related_name='+',on_delete=models.DO_NOTHING)

    def __str__(self):
        truncated_message = Truncator(self.message)
        return truncated_message.chars(30)

    def get_message_as_markdown(self):
        return mark_safe(markdown(self.message,safe_mode='escape'))


#end of l code

boards/forms.py
from django import forms
from .models import Topic,Post

class NewTopicForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(attrs={'rows': 5, 'placeholder': 'What is on your mind?'}),
                              max_length= 4000,
                              help_text='The max length of the text is 4000.')

    class Meta:
        model = Topic
        fields = ['subject','message']

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message']

templates/base.html
{% load static %}<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Django Boards{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    {% block stylesheet %}{% endblock %}
</head>
<body>
{% block body %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu"
                aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                        <a class="dropdown-item" href="#">My account</a>
                        <a class="dropdown-item" href="#">Change password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <form class="form-inline ml-auto">
                <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
                <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
            </form>
            {% endif %}
        </div>
    </div>
</nav>

<div class="container">
    <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
    </ol>
    {% block content %}
    {% endblock %}
</div>
{% endblock body %}
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block javascript %}{% endblock %}
</body>
</html>

templates/base_accounts.html
{% extends 'base.html' %}
{% load static %}
{% block stylesheet %}
   <link href="{% static 'css/accounts.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}
   <div class="container">
      <h1 class="text-center logo my-4">
         <a href="{% url 'home' %}">Django Boards</a>
      </h1>
       {% block content %}
       {% endblock %}
   </div>
{% endblock body %}

templates/edit_post.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Edit post{% endblock %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/simplemde.min.css' %}">
{% endblock %}

{% block javascript %}
  <script src="{% static 'js/simplemde.min.js' %}"></script>
  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'board_topics' post.topic.board.pk %}">{{ post.topic.board.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'topic_posts' post.topic.board.pk post.topic.pk %}">{{ post.topic.subject }}</a></li>
    <li class="breadcrumb-item active">Edit post</li>
{% endblock %}

{% block content %}
    <form method="post" class="mb-4" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Save changes</button>
        <a href="{% url 'topic_posts' post.topic.board.pk post.topic.pk %}" class="btn btn-outline secondary" role="button">Cancel</a>
    </form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block breadcrumb %}
<li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block content %}
<table class="table">
    <thead class="thead-inverse">
    <tr>
        <th>Board</th>
        <th>Posts</th>
        <th>Topics</th>
        <th>Last Post</th>
    </tr>
    </thead>
    <tbody>
    {% for board in boards %}
    <tr>
        <td>
            <a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
            <small class="text-muted d-block">{{ board.description }}</small>
        </td>
        <td class="align-middle">
            {{ board.get_posts_count }}
        </td>
        <td class="align-middle">
            {{ board.topics.count }}
        </td>
        <td class="align-middle">
            {% with post=board.get_last_post %}
            {% if post %}
              <small>
                <a href="{% url 'topic_posts' board.pk post.topic.pk %}">
                    By {{ post.created_by.username }} at {{ post.created_at }}
                </a>
              </small>
            {% else %}
              <small class="text-muted">
                <em>No posts yet.</em>
              </small>
            {% endif %}
            {% endwith %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}


<!--
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Boards</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
&lt;!&ndash;    <h1>Board</h1>&ndash;&gt;
    <div class="container">
      <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active">Boards</li>
      </ol>
    <table class = "table">
      <thead class = 'thead-inverse'>
        <tr>
          <th>Board</th>
          <th>Posts</th>
          <th>Topics</th>
          <th>Last Post</th>
        </tr>
      </thead>
      <tbody>
        {% for board in boards %}
          <tr>
            <td>
&lt;!&ndash;              {{ board.name }}<br>&ndash;&gt;
                <a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
              <small class='text-muted d-block'>{{ board.description }}</small>
            </td>
            <td class="align-middle">0</td>
            <td class="align-middle">0</td>
            <td></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
</body>
</html>
-->

templates/login.html
{% extends 'base_accounts.html' %}

{% block title %}Log in to Django Boards{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Log in</h3>
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% include 'includes/form.html' %}
                    <button type="submit" class="btn btn-primary btn-block">Log in</button>
                </form>
            </div>
            <div class="card-footer text-muted text-center">
                New to Django Boards? <a href="{% url 'signup' %}">Sign up</a>
            </div>
        </div>
        <div class="text-center py-2">
            <small>
                <a href="#" class="text-muted">Forgot your password?</a>
            </small>
        </div>
    </div>
</div>
{% endblock %}

templates/my_account.html
{% extends 'base.html' %}

{% block title %}My account{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">My account</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <form method="post" novalidate>
                {% csrf_token %}
                {% include 'includes/form.html' %}
                <button type="submit" class="btn btn-success">Save changes</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/new_topic.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Start a new topic{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
<li class="breadcrumb-item"><a href="{% url 'board_topics' board.pk %}">{{board.name}}</a></li>
<li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}
<form method="post" novalidate>
    {% csrf_token %}

<!--    <div class="form-group">-->
<!--        <label for="id_subject">Subject</label>-->
<!--        <input type="text"  id = "id_subject" name = 'subject' class="form-control">-->
<!--    </div>-->
<!--    <div class="form-group">-->
<!--        <label for="id_message">Message</label>-->
<!--        <textarea class="form-control" id = "id_message" name = "message" rows="5"></textarea>-->
<!--    </div>-->

<!--    {{ form.as_p }}-->
<!--    {% for field in form %}-->
<!--      <div class="form-group">-->
<!--        {{ field.label_tag }}-->
<!--        {% if form.is_bound %}-->
<!--            {% if field.errors %}-->
<!--                {% render_field field class="form-control is-invalid" %}-->
<!--                {% for error in field.errors %}-->
<!--                    <div class="invalid-feedback">-->
<!--                        {{ error }}-->
<!--                    </div>-->
<!--                {% endfor %}-->
<!--            {% else %}-->
<!--                {% render_field field class="form-control is-valid" %}-->
<!--            {% endif %}-->
<!--        {% else %}-->
<!--            {% render_field field class="form-control" %}-->
<!--        {% endif %}-->
<!--        {% if field.help_text %}-->
<!--          <small class="form-text text-muted">-->
<!--            {{ field.help_text }}-->
<!--          </small>-->
<!--        {% endif %}-->
<!--      </div>-->
<!--    {% endfor %}-->
    {% include "includes/form.html" %}
    <button type="submit" class="btn btn-success">Post</button>
</form>
{% endblock %}

templates/password_change.html
{% extends 'base.html' %}

{% block title %}Change Password{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <form method="post" novalidate>
                {% csrf_token %}
                {% include 'includes/form.html' %}
                <button type="submit" class="btn btn-success">Change password</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/password_reset.html
{% extends 'base_accounts.html' %}
{% block title %}Password Reset {% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-8">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Reset your password</h3>
                    <p>Enter your email address and we will send you a link to reset your password.</p>
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% include 'includes/form.html' %}
                        <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/password_reset_confirm.html
{% extends 'base_accounts.html' %}

{% block title %}
{% if validlink %}
Change password for {{ form.user.username }}
{% else %}
Reset your password
{% endif %}
{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <div class="card">
            <div class="card-body">
                {% if validlink %}
                <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% include 'includes/form.html' %}
                    <button type="submit" class="btn btn-success btn-block">Change password</button>
                </form>
                {% else %}
                <h3 class="card-title">Reset your password</h3>
                <div class="alert alert-danger" role="alert">
                    It looks like you clicked on an invalid password reset link. Please try again.
                </div>
                <a href="{% url 'password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset
                    link</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/password_reset_done.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
          <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Boards username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The Django Boards Team

templates/signup.html
{% extends 'base_accounts.html' %}

{% block title %}Sign up to Django Boards{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Sign up</h3>
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% include 'includes/form.html' %}
                    <button type="submit" class="btn btn-primary btn-block">Create an account</button>
                </form>
            </div>
            <div class="card-footer text-muted text-center">
                Already have an account<a href="{% url 'login' %}">Log in</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/topic_posts.html
{% extends 'base.html' %}
{% load static %}
{% load gravatar %}

{% block title %}{{ topic.subject }}{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
<li class="breadcrumb-item"><a href="{% url 'board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
<li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}

{% block content %}
<div class="mb-4">
    <a href="{% url 'reply_topic' topic.board.pk topic.pk %}" class="btn btn-primary" role="button">Reply</a>
</div>

{% for post in posts %}
<div id = {{ post.pk }} class="card mb-2 {% if forloop.first %}border-dark{% endif %}">
    {% if forloop.first %}
        <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
    {% endif %}
    <div class="card-body p-3">
        <div class="row">
            <div class="col-2">
                <img src="{{ post.created_by|gravatar }}" alt="{{ post.created_by.username }}" class="w-100 rounded">
                <small>Posts: {{ post.created_by.posts.count }}</small>
            </div>
            <div class="col-10">
                <div class="row mb-3">
                    <div class="col-6">
                        <strong class="text-muted">{{ post.created_by.username }}</strong>
                    </div>
                    <div class="col-6 text-right">
                        <small class="text-muted">{{ post.created_at }}</small>
                    </div>
                </div>
                {{ post.get_message_as_markdown }}
                {% if post.created_by == user %}
                <div class="mt-3">
                    <a href="{% url 'edit_post' post.topic.board.pk post.topic.pk post.pk %}" class="btn btn-primary btn-sm" role="button">Edit</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% include 'includes/pagination.html' %}

{% endblock %}